require './app/models/horse.rb'

Horse.create!(name: "Penelope", age: 29, total_winnings: 34000, jockey_id:5)
Horse.create!(name: "Penelope", age: 39, total_winnings: 500, jockey_id:2)
Horse.create!(name: "Paulo", age: 45, total_winnings: 45000, jockey_id:2)
Horse.create!(name: "Pepe", age: 39, total_winnings: 1000000, jockey_id:6)
Horse.create!(name: "Pete", age: 55, total_winnings: 4000, jockey_id:1)
Horse.create!(name: "Paige", age: 20, total_winnings: 78000, jockey_id:1)
Horse.create!(name: "Peyton", age: 95, total_winnings: 898344, jockey_id:1)
Horse.create!(name: "Patricia", age: 49, total_winnings: 78000, jockey_id:3)
Horse.create!(name: "Patricia", age: 49, total_winnings: 8978000, jockey_id:4)
Horse.create!(name: "Picasso", age: 15, total_winnings: 78000, jockey_id:5)
Jockey.create!(name: "Lee Unkrich")
Jockey.create!(name: "George Lucas")
Jockey.create!(name: "Christopher Nolan")
Jockey.create!(name: "Joss Whedon")
Jockey.create!(name: "Colin Trevorrow")
Jockey.create!(name: "James Cameron")
